"use client";
import React, { useState, useEffect } from 'react';
import { auth, db } from '@/lib/firebase';
import { doc, onSnapshot } from 'firebase/firestore';
import LoadingSpinner from '@/components/LoadingSpinner';

const AIPaint = () => {
  const [prompt, setPrompt] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [project, setProject] = useState<any | null>(null);

  // Real-time listener for project status updates
  useEffect(() => {
    if (!project?.id) return;

    const unsub = onSnapshot(doc(db, "ai_projects", project.id), (doc) => {
      if (doc.exists()) {
        setProject({ id: doc.id, ...doc.data() });
        if (doc.data().status === 'completed' || doc.data().status === 'failed') {
          setLoading(false);
        }
      }
    });

    return () => unsub();
  }, [project?.id]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!prompt) {
      setError('Please enter a prompt.');
      return;
    }
    const user = auth.currentUser;
    if (!user) {
      setError('You must be logged in to use this feature.');
      return;
    }

    setLoading(true);
    setError(null);
    setProject(null);

    try {
      const idToken = await user.getIdToken();
      const res = await fetch('/api/ai/paint', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${idToken}`,
        },
        body: JSON.stringify({ prompt }),
      });

      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.detail || 'Failed to start image generation.');
      }

      // Set the initial project state to start listening for real-time updates
      setProject({ id: data.projectId, status: 'queued' });

    } catch (err: any) {
      setError(err.message);
      setLoading(false);
    }
  };

  const renderProjectStatus = () => {
    if (!project) return null;
    
    switch (project.status) {
      case 'queued':
        return <p>✅ Your request is in the queue. Processing will begin shortly.</p>;
      case 'processing':
        return <p>⚙️ Generating your image... Progress: {project.progress || 0}%</p>;
      case 'completed':
        return (
          <div>
            <h3>✨ Generation Complete!</h3>
            <img src={project.public_url} alt="Generated by AI" style={{ maxWidth: '100%', borderRadius: '10px', marginTop: '10px' }} />
          </div>
        );
      case 'failed':
        return <p style={{ color: 'red' }}>❌ Generation failed. Your credits have been refunded.</p>;
      default:
        return null;
    }
  }

  return (
    <div style={{ padding: '20px', color: '#333', background: '#fff', height: '100%', overflowY: 'auto' }}>
      <h2>ADANID-Paint: AI Image Generator</h2>
      <p>Enter a prompt to generate an image. This action will reserve 5 AI credits.</p>
      <form onSubmit={handleSubmit} style={{ display: 'flex', gap: '10px', marginBottom: '20px' }}>
        <input
          type="text"
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="e.g., A majestic lion in a field of stars"
          style={{ flexGrow: 1, padding: '10px', borderRadius: '5px', border: '1px solid #ccc' }}
          disabled={loading}
        />
        <button type="submit" disabled={loading} style={{ padding: '10px 15px', borderRadius: '5px', border: 'none', background: '#007bff', color: 'white', cursor: 'pointer' }}>
          {loading ? 'Queueing...' : 'Generate'}
        </button>
      </form>

      {loading && !project?.status && <LoadingSpinner />}
      {error && <div style={{ color: 'red', marginTop: '10px' }}>Error: {error}</div>}
      
      {project && (
        <div style={{ marginTop: '20px' }}>
          {renderProjectStatus()}
        </div>
      )}
    </div>
  );
};

export default AIPaint;
